---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(assertthat)

```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

# My function

```{r function-bmi}
#' bmi 
#' 
#' Function calculation the Body Mass Index
#'
#' @importFrom assertthat assert_that
#'
#' @param mass weight value in kg (should be between 0 and 200)
#' @param height height value in meter (should be between 0. and 2.5)
#'
#' @return The Body Mass Index in kg/m2
#' @export
#'
bmi <- function(mass, height) {
  if(is.na(mass) | is.na(height)){
    return(message('NA value'))
  }else{
    assert_that(mass > 0 & mass < 200)
    assert_that(height > 0.5 & height < 2.5)

    bmi_to_return <- mass/height^2
    return(bmi_to_return)
  }
}
```

```{r examples-bmi}
bmi(mass = 70, height = 1.8)
```

```{r tests-bmi}
test_that("bmi works", {
  expect_equal(bmi(mass = 70, height = 1.8), 70/(1.8^2))
  expect_error(bmi(mass = 3000, height = 1.8))
  expect_error(bmi(mass = 70, height = 180))
  expect_message(bmi(mass = NA, height = 180), 'NA value')
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_minimal.Rmd", vignette_name = "BMI")
```
