---
title: "flat_additional.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(readxl)
library(purrr)
```

```{r development-1}
# Load already included functions
pkgload::load_all(export_all = FALSE)
```

# My function

```{r function-multi_import_excel}
#' multi_import_excel Title
#'
#' @param path path to the xlsx file to read
#'
#' @importFrom purrr map set_names
#' @importFrom readxl read_excel excel_sheets
#'
#' @return list containing all the xlsx file spreadsheet tables
#' @export
#'
multi_import_excel <- function(path) {
  list_spreadsheet <- path %>% 
                      excel_sheets() %>% 
                      set_names() %>% 
                      map(read_excel, path = path)
  return(list_spreadsheet)
}
```

```{r multi_import_excel-multi_import_excel}
mypath <- system.file("extdata", "toydatasets.xlsx", package = "aurelienmace")
multi_import_excel(path = mypath)
```

```{r tests-multi_import_excel}
test_that("my_fun works", {
  mypath <- system.file("extdata", "toydatasets.xlsx", package = "aurelienmace")
  test_res <- multi_import_excel(path = mypath) %>% map(dim)
  expect_equal(test_res$diamonds, c(50, 10))

})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_additional.Rmd", vignette_name = "Go further")
```

