# Generated by fusen: do not edit by hand

test_that("my_fun works", {
  mypath <- system.file("extdata", "toydatasets.xlsx", package = "aurelienmace")
  test_res <- multi_import_excel(path = mypath) %>% map(dim)
  expect_equal(test_res$diamonds, c(50, 10))

})
