# Generated by fusen: do not edit by hand

#' bmi 
#' 
#' Function calculation the Body Mass Index
#'
#' @importFrom assertthat assert_that
#'
#' @param mass weight value in kg (should be between 0 and 200)
#' @param height height value in meter (should be between 0. and 2.5)
#'
#' @return The Body Mass Index in kg/m2
#' @export
#'
#' @examples
#' bmi(mass = 70, height = 1.8)
bmi <- function(mass, height) {
  if(is.na(mass) | is.na(height)){
    return(message('NA value'))
  }else{
    assert_that(mass > 0 & mass < 200)
    assert_that(height > 0.5 & height < 2.5)

    bmi_to_return <- mass/height^2
    return(bmi_to_return)
  }
}
