# Generated by fusen: do not edit by hand

#' multi_import_excel Title
#'
#' @param path path to the xlsx file to read
#'
#' @importFrom purrr map set_names
#' @importFrom readxl read_excel excel_sheets
#'
#' @return list containing all the xlsx file spreadsheet tables
#' @export
#'
multi_import_excel <- function(path) {
  list_spreadsheet <- path %>% 
                      excel_sheets() %>% 
                      set_names() %>% 
                      map(read_excel, path = path)
  return(list_spreadsheet)
}
